
[workspace]

members = [
  "src/batsat",
  "src/batsat-bin",
  "src/batsat-ipasir",
]

default-members = [
  "src/batsat",
  "src/batsat-bin"
]

[profile.release]
opt-level = 3
lto = true # helps a lot with inlining

# for `perf`:
# debug = true 

[profile.dev]
opt-level = 1
