[package]
name = "batsat-sudoku"
version = "0.1.0"
authors = ["Simon Cruanes <simon.cruanes.2007@m4x.org>"]
edition = "2018"

[dependencies]

log = "^0.4"
env_logger = "^0.5"
batsat = { path="../batsat", features = ["logging"] }
