[package]
name = "batsat-stubs"
version = "0.1.0"
authors = ["Simon Cruanes"]

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]

ocaml = "0.5"
#ocaml = {version="0.5", path = "/home/simon/workspace/ocaml-rs"}
batsat = {path = "../batsat/", features=[]}

[workspace]

