[package]
name = "platsat-sudoku"
version = "0.1.0"
authors = ["Simon Cruanes <simon.cruanes.2007@m4x.org>"]
edition = "2018"

publish = false

[dependencies]

log = "^0.4"
env_logger = {version="^0.5", default-features=false}
platsat = { path= "../platsat", features = ["logging"] }
